POST http://localhost:3000/test/testRequestBodyData 
Content-Type: application/json

{
  "name": "Test Product",
  "price": 19.99,
  "description": "This is a test product for validating request body data."
}

###
POST http://localhost:3000/test/testRequestBodyData 
Content-Type: application/json

{
  "name": "Test Product",
  "age": 19,
  "email": "sar888@gmai.com"
}