GET http://localhost:3000/products

###
GET http://localhost:3000/products/{id}

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "productName": "123",
  "category" : "1"
}

###
PUT http://localhost:3000/products/{id}
{
  "name": "string",
  "description": "string",
  "price": 0,
  "category": "string"
}

###
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createProduct(input: { name: \"Test\", description: \"Desc\", price: 20.0 }) { id name } }"
}
