# jobs:
#   build:
#     name: Build and Test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         use: action/checkout@v4
#       - name: Set up Node JS environment
#         use: action/setup-node@v4
#         whit:
#           node-version: 20
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Build
#         run: pnpm build
