name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DATABASE_THREE_URL: ${{ secrets.DATABASE_THREE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      # Install Playwright browsers for CI
      - run: pnpm exec playwright install --with-deps
      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      - run: pnpm prisma generate --schema=libs/my-prisma-schema/prisma/schema.prisma

      - run: pnpm exec nx run-many -t test lint build e2e -p web* api-gateway* ecomapp
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      # - run: pnpm exec nx fix-ci
      #   if: always()

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Build web
      - name: Build web Docker image
        run: docker build -f apps/web/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/web:latest .

      # ✅ Build api-gateway
      - name: Build api-gateway Docker image
        run: docker build -f apps/api-gateway/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest .

      # ✅ Push images
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/web:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
